"""Typed Python facade for deterministic derivatives valuation."""

from collections.abc import Sequence
from datetime import date
from typing import Literal

DateLike = date | str
OptionSide = Literal["call", "put"]
DigitalPayout = Literal["cash", "asset"]
BarrierDirection = Literal["up", "down"]
BarrierStyle = Literal["knock_in", "knock_out"]
BarrierMonitoring = Literal["discrete", "continuous"]
SmileDynamics = Literal[
    "sticky_log_moneyness", "sticky_strike", "sticky_delta"
]
LsmStateVariable = Literal["spot"]
ExerciseStrategyRisk = Literal["fixed_exercise_strategy"]
StoppingIndexRisk = Literal["frozen_stopping_indices"]
RandomDomain = Literal["valuation", "lsm_train", "rqmc_scramble", "diagnostics"]
LsmWarningKind = Literal[
    "zero_itm_training_paths", "inactive_feature", "rank_excluded_basis_column"
]
ExerciseDecisionKind = Literal["regression", "continue_all"]
ValidationPhase = Literal[
    "syntax_and_limits",
    "declared_schema",
    "migration",
    "current_schema",
    "domain",
]
VegaKtCovarianceLayout = Literal[
    "price_and_bucket_variance_only", "full_bucket_matrix_row_major"
]
VegaKtUnit = Literal[
    "currency_per_unit_absolute_volatility", "currency_per_volatility_point"
]
RiskUnit = Literal[
    "delta_raw",
    "delta_one_percent_spot",
    "gamma_raw",
    "gamma_one_percent_spot_squared",
    "vega_raw",
    "vega_one_vol_point",
]

__version__: str


class RoughBergomiModel:
    """Riemann-Liouville rough Bergomi; vol_of_vol is the log-variance coefficient eta."""
    def __init__(self, hurst: float, vol_of_vol: float, *, equity_vol_correlation: float) -> None: ...
    @property
    def hurst(self) -> float: ...
    @property
    def vol_of_vol(self) -> float: ...
    @property
    def equity_vol_correlation(self) -> float: ...


class HullWhiteModel:
    """One-factor HW: constant mean reversion and piecewise constant rate volatility."""
    def __init__(
        self, mean_reversion: float, volatility_times: Sequence[float],
        volatilities: Sequence[float],
    ) -> None: ...
    @property
    def mean_reversion(self) -> float: ...
    @property
    def volatility_times(self) -> list[float]: ...
    @property
    def volatilities(self) -> list[float]: ...
    def bond_price(
        self, discount_curve: DiscountCurve, time: float, maturity: float,
        rate_factor: float,
    ) -> float: ...
    def bond_option(
        self, discount_curve: DiscountCurve, expiry: float, maturity: float,
        strike: float, *, is_call: bool = True,
    ) -> float: ...


class HullWhiteLsvTarget:
    """Paired Dupire variance and T-forward log-density calibration samples."""
    @staticmethod
    def from_market_iv(
        maturity_nodes: Sequence[float], quote_log_moneyness_nodes: Sequence[float],
        implied_volatilities: Sequence[float], time_nodes: Sequence[float],
        log_moneyness_nodes: Sequence[float], *, floor: float = 1e-8, cap: float = 4.0,
    ) -> HullWhiteLsvTarget: ...
    @property
    def supports_vega_kt(self) -> bool: ...
    @staticmethod
    def flat(
        volatility: float, time_nodes: Sequence[float],
        log_moneyness_nodes: Sequence[float], *, floor: float = 1e-8, cap: float = 4.0,
    ) -> HullWhiteLsvTarget: ...
    @staticmethod
    def from_essvi(
        slices: Sequence[EssviSlice], terminal_theta_slope: float,
        time_nodes: Sequence[float], log_moneyness_nodes: Sequence[float], *,
        floor: float = 1e-8, cap: float = 4.0,
    ) -> HullWhiteLsvTarget: ...
    @staticmethod
    def from_grid(model: Model, forward_log_densities: Sequence[float]) -> HullWhiteLsvTarget: ...
    @property
    def model(self) -> Model: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def forward_log_densities(self) -> list[float]: ...


class HullWhiteEquityPlan:
    """Experimental BS/Bergomi/rough Bergomi + HW, LSV and escrowed cash dividends."""
    @staticmethod
    def compile_bergomi(
        request: PricingRequest, rate_model: HullWhiteModel, *,
        vol_mean_reversion: float, vol_of_vol: float, equity_vol_correlation: float,
        equity_rate_correlation: float, vol_rate_correlation: float, maximum_step: float,
        worker_threads: int, reduction_block_size: int | None = None,
    ) -> HullWhiteEquityPlan: ...
    @staticmethod
    def compile_bergomi_two_factor(
        request: PricingRequest, rate_model: HullWhiteModel, *,
        mean_reversions: Sequence[float], vol_of_vol: float, mixing_weight: float,
        spot_correlations: Sequence[float], factor_correlation: float,
        equity_rate_correlation: float, vol_rate_correlations: Sequence[float],
        maximum_step: float, worker_threads: int, reduction_block_size: int | None = None,
    ) -> HullWhiteEquityPlan: ...
    @staticmethod
    def compile_rough_bergomi(
        request: PricingRequest, rough_model: RoughBergomiModel, rate_model: HullWhiteModel, *,
        equity_rate_correlation: float, vol_rate_correlation: float, maximum_step: float,
        worker_threads: int, reduction_block_size: int | None = None,
        cash_dividend_model: Literal["escrowed"] | None = None,
    ) -> HullWhiteEquityPlan: ...
    @staticmethod
    def compile_rough_lsv(
        request: PricingRequest, target: HullWhiteLsvTarget,
        rough_model: RoughBergomiModel, rate_model: HullWhiteModel, *,
        equity_rate_correlation: float, vol_rate_correlation: float, particle_count: int,
        calibration_seed: int, log_bandwidth: float, minimum_effective_samples: float,
        worker_threads: int, reduction_block_size: int | None = None,
        cash_dividend_model: Literal["escrowed"] | None = None,
        retain_reverse_trace: bool = False,
    ) -> HullWhiteEquityPlan: ...
    @property
    def random_factor_count(self) -> int: ...
    @staticmethod
    def compile_bs(
        request: PricingRequest, rate_model: HullWhiteModel, *,
        equity_rate_correlation: float, maximum_step: float, worker_threads: int,
        reduction_block_size: int | None = None,
        cash_dividend_model: Literal["escrowed"] | None = None,
    ) -> HullWhiteEquityPlan: ...
    @staticmethod
    def compile_lsv(
        request: PricingRequest, target: HullWhiteLsvTarget, rate_model: HullWhiteModel, *,
        vol_mean_reversion: float, vol_of_vol: float, equity_vol_correlation: float,
        equity_rate_correlation: float, vol_rate_correlation: float,
        particle_count: int, calibration_seed: int, log_bandwidth: float,
        minimum_effective_samples: float, worker_threads: int,
        reduction_block_size: int | None = None,
        cash_dividend_model: Literal["escrowed"] | None = None,
        retain_reverse_trace: bool = False,
    ) -> HullWhiteEquityPlan: ...
    @staticmethod
    def compile_lsv_two_factor(
        request: PricingRequest, target: HullWhiteLsvTarget, rate_model: HullWhiteModel, *,
        mean_reversions: Sequence[float], vol_of_vol: float, mixing_weight: float,
        spot_correlations: Sequence[float], factor_correlation: float,
        equity_rate_correlation: float, vol_rate_correlations: Sequence[float],
        particle_count: int, calibration_seed: int, log_bandwidth: float,
        minimum_effective_samples: float, worker_threads: int,
        reduction_block_size: int | None = None,
        cash_dividend_model: Literal["escrowed"] | None = None,
        retain_reverse_trace: bool = False,
    ) -> HullWhiteEquityPlan: ...
    def evaluate(self) -> HullWhitePrice: ...
    def evaluate_aad(self) -> HullWhiteAadRisk: ...
    @property
    def retains_reverse_trace(self) -> bool: ...
    @property
    def cash_dividend_model(self) -> str | None: ...
    @property
    def risky_spot(self) -> float: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float] | None: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...
    @property
    def fallback_nodes(self) -> list[int]: ...
    @property
    def calibration_discount_means(self) -> list[float]: ...
    @property
    def calibration_discounted_equity_means(self) -> list[float]: ...


class StochasticDividendPlan:
    """Buehler cash dividends, constant residual volatility and deterministic carry.

    Fixed-cash market amounts are Q-means; only price-only requests are accepted.
    Correlation is between residual-equity and dividend Brownian drivers.
    """
    @staticmethod
    def compile_bs(
        request: PricingRequest, *, mean_reversion: float, equity_linkage: float,
        dividend_volatility: float, equity_dividend_correlation: float,
        maximum_step: float, worker_threads: int, reduction_block_size: int | None = None,
    ) -> StochasticDividendPlan: ...
    @staticmethod
    def compile_bergomi(request: PricingRequest, *, mean_reversion: float, vol_of_vol: float, correlation: float, dividend_mean_reversion: float, equity_linkage: float, dividend_volatility: float, equity_dividend_correlation: float, dividend_volatility_correlation: float, maximum_step: float, worker_threads: int, reduction_block_size: int | None = None) -> StochasticDividendPlan: ...
    @staticmethod
    def compile_bergomi_two_factor(request: PricingRequest, *, mean_reversions: Sequence[float], vol_of_vol: float, mixing_weight: float, spot_correlations: Sequence[float], factor_correlation: float, dividend_mean_reversion: float, equity_linkage: float, dividend_volatility: float, equity_dividend_correlation: float, dividend_volatility_correlations: Sequence[float], maximum_step: float, worker_threads: int, reduction_block_size: int | None = None) -> StochasticDividendPlan: ...
    def evaluate(self) -> StochasticDividendPrice: ...
    def evaluate_aad(self) -> StochasticDividendAadRisk: ...
    def evaluate_bergomi_aad(self) -> StochasticDividendAadRisk: ...
    def evaluate_correlation_aad(self) -> StochasticDividendAadRisk: ...
    def evaluate_gamma(self, *, gamma_absolute_bump: float | None = None, gamma_relative_bump: float | None = None) -> StochasticDividendGammaRisk: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def random_factor_count(self) -> int: ...
    @property
    def risky_spot(self) -> float: ...
    @property
    def scheme(self) -> str: ...


class StochasticDividendAadRisk:
    """Raw first derivatives; sigma0 Vega is not market-IV VegaKT."""
    @property
    def price(self) -> StochasticDividendPrice: ...
    @property
    def parameter_labels(self) -> list[str]: ...
    @property
    def derivatives(self) -> list[float]: ...
    @property
    def standard_errors(self) -> list[float]: ...
    @property
    def cash_times(self) -> list[float]: ...
    @property
    def discount_times(self) -> list[float]: ...
    @property
    def repo_spread_times(self) -> list[float]: ...
    @property
    def method(self) -> str: ...
    @property
    def uncertainty_scope(self) -> str: ...
    @property
    def delta(self) -> float: ...
    @property
    def initial_volatility_vega(self) -> float: ...
    @property
    def initial_volatility_vega_per_vol_point(self) -> float: ...
    @property
    def dividend_volatility_vega_per_vol_point(self) -> float: ...
    @property
    def cash_mean_adjoints(self) -> list[float]: ...
    @property
    def discount_node_dv01(self) -> list[float]: ...
    @property
    def repo_spread_node_dv01(self) -> list[float]: ...


class StochasticDividendGammaRisk:
    """Common-noise central-bump AAD Delta with a half/base/double bump ladder."""
    @property
    def price(self) -> StochasticDividendPrice: ...
    @property
    def delta(self) -> float: ...
    @property
    def delta_standard_error(self) -> float: ...
    @property
    def spot(self) -> float: ...
    @property
    def spot_bumps(self) -> list[float]: ...
    @property
    def gamma(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def gamma_estimates(self) -> list[float]: ...
    @property
    def gamma_standard_errors(self) -> list[float]: ...
    @property
    def bump_differences(self) -> list[float]: ...
    @property
    def bump_difference_standard_errors(self) -> list[float]: ...
    @property
    def payoff_evaluations(self) -> int: ...
    @property
    def risk_fingerprint(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def delta_change_per_one_percent_spot(self) -> float: ...
    @property
    def uncertainty_scope(self) -> str: ...


class StochasticDividendPrice:
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def independent_sampling_units(self) -> int: ...
    @property
    def evaluated_paths(self) -> int: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def uncertainty_scope(self) -> Literal["pricing_only"]: ...


class StochasticVolatilityPlan:
    """Pure 1F/2F/rough Bergomi, deterministic curves and flat initial variance.

    The BlackScholes request supplies sigma0. No LV target or particles.
    Markovian vol_of_vol is nu (log volatility); rough uses eta (log variance).
    """
    @staticmethod
    def compile_bergomi(
        request: PricingRequest, *, mean_reversion: float, vol_of_vol: float,
        correlation: float, maximum_step: float, worker_threads: int,
        reduction_block_size: int | None = None,
    ) -> StochasticVolatilityPlan: ...
    @staticmethod
    def compile_bergomi_two_factor(
        request: PricingRequest, *, mean_reversions: Sequence[float], vol_of_vol: float,
        mixing_weight: float, spot_correlations: Sequence[float], factor_correlation: float,
        maximum_step: float, worker_threads: int, reduction_block_size: int | None = None,
    ) -> StochasticVolatilityPlan: ...
    @staticmethod
    def compile_rough_bergomi(
        request: PricingRequest, rough_model: RoughBergomiModel, *, maximum_step: float,
        worker_threads: int, reduction_block_size: int | None = None,
    ) -> StochasticVolatilityPlan: ...
    def evaluate(self) -> HullWhitePrice: ...
    def evaluate_aad(self) -> HullWhiteAadRisk: ...
    @property
    def cash_dividend_model(self) -> str | None: ...
    @property
    def risky_spot(self) -> float: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def random_factor_count(self) -> int: ...


class HullWhitePrice:
    @property
    def cash_dividend_model(self) -> str | None: ...
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def independent_sampling_units(self) -> int: ...
    @property
    def evaluated_paths(self) -> int: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def calibration_method(self) -> str | None: ...
    @property
    def calibration_seed(self) -> int | None: ...
    @property
    def uncertainty_scope(self) -> Literal["pricing_only", "pricing_conditional_on_calibration"]: ...



class HullWhiteAadRisk:
    """Finite hybrid AAD at fixed model parameters and paired-target coordinates."""
    @property
    def vega_kt_raw(self) -> list[float] | None: ...
    @property
    def vega_kt_market_scaled(self) -> list[float] | None: ...
    @property
    def vega_kt_standard_errors(self) -> list[float] | None: ...
    @property
    def parallel_vega_standard_error(self) -> float | None: ...
    @property
    def vega_kt_maturity_nodes(self) -> list[float]: ...
    @property
    def vega_kt_log_moneyness_nodes(self) -> list[float]: ...
    @property
    def vega_kt_implied_volatilities(self) -> list[float]: ...
    @property
    def vega_kt_method(self) -> str | None: ...
    @property
    def price(self) -> HullWhitePrice: ...
    @property
    def parameter_labels(self) -> list[str]: ...
    @property
    def derivatives(self) -> list[float]: ...
    @property
    def standard_errors(self) -> list[float] | None: ...
    @property
    def delta(self) -> float: ...
    @property
    def vega(self) -> float | None: ...
    @property
    def discount_times(self) -> list[float]: ...
    @property
    def dividend_times(self) -> list[float]: ...
    @property
    def discount_log_df_adjoints(self) -> list[float]: ...
    @property
    def dividend_log_df_adjoints(self) -> list[float]: ...
    @property
    def discount_node_dv01(self) -> list[float]: ...
    @property
    def parallel_discount_dv01(self) -> float: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def local_variance_adjoints(self) -> list[float]: ...
    @property
    def forward_log_density_adjoints(self) -> list[float]: ...
    @property
    def method(self) -> str: ...
    @property
    def uncertainty_scope(self) -> Literal["pricing_only", "pricing_conditional_on_calibration"]: ...


class BergomiLsvPlan:
    """Experimental LSV calibration and independent MC/RQMC pricing plan."""
    @staticmethod
    def compile(
        target_request: PricingRequest, *, mean_reversion: float, vol_of_vol: float,
        correlation: float, particle_count: int, calibration_seed: int,
        log_bandwidth: float, minimum_effective_samples: float,
        retain_reverse_trace: bool, worker_threads: int,
        reduction_block_size: int | None = None,
    ) -> BergomiLsvPlan: ...
    def evaluate(self) -> LsvPrice: ...
    def evaluate_local_variance_risk(self) -> LsvLocalVarianceRisk: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float]: ...
    @property
    def extrapolated_moment_nodes(self) -> list[int]: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...


class Bergomi2FactorLsvPlan:
    """Experimental LSV calibration and independent MC/RQMC pricing plan."""
    @staticmethod
    def compile(
        target_request: PricingRequest, *, mean_reversions: Sequence[float], vol_of_vol: float,
        mixing_weight: float, spot_correlations: Sequence[float], factor_correlation: float, particle_count: int, calibration_seed: int,
        log_bandwidth: float, minimum_effective_samples: float,
        retain_reverse_trace: bool, worker_threads: int,
        reduction_block_size: int | None = None,
    ) -> Bergomi2FactorLsvPlan: ...
    def evaluate(self) -> LsvPrice: ...
    def evaluate_local_variance_risk(self) -> LsvLocalVarianceRisk: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float]: ...
    @property
    def extrapolated_moment_nodes(self) -> list[int]: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...


class RoughBergomiLsvPlan:
    """Experimental deterministic-rate rough Bergomi LSV calibration and pricing plan.

    ``vol_of_vol`` is eta, the coefficient of log variance, as for ``RoughBergomiModel``.
    """
    @staticmethod
    def compile(
        target_request: PricingRequest, *, hurst: float, vol_of_vol: float,
        correlation: float, particle_count: int, calibration_seed: int,
        log_bandwidth: float, minimum_effective_samples: float,
        retain_reverse_trace: bool, worker_threads: int,
        reduction_block_size: int | None = None,
    ) -> RoughBergomiLsvPlan: ...
    def evaluate(self) -> LsvPrice: ...
    def evaluate_local_variance_risk(self) -> LsvLocalVarianceRisk: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float]: ...
    @property
    def extrapolated_moment_nodes(self) -> list[int]: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...


class LsvPrice:
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def independent_sampling_units(self) -> int: ...
    @property
    def evaluated_paths(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def uncertainty_scope(self) -> Literal["pricing_conditional_on_calibration"]: ...


class LsvLocalVarianceRisk:
    """Row-major derivatives w.r.t. effective relative Dupire variance nodes."""
    @property
    def price(self) -> LsvPrice: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def node_adjoints(self) -> list[float]: ...
    @property
    def standard_errors(self) -> list[float] | None: ...
    @property
    def method(self) -> str: ...
    @property
    def coordinate(self) -> Literal["relative_dupire_variance_nodes_in_f"]: ...


class ValidationIssue:
    @property
    def pointer(self) -> str: ...
    @property
    def instance_path(self) -> str: ...
    @property
    def phase(self) -> ValidationPhase: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def document_kind(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...


class ValidationError(ValueError):
    issues: list[ValidationIssue]


class PricingError(RuntimeError): ...


class PricingWarning:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    def __repr__(self) -> str: ...


class DiagnosticEstimate:
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def confidence_interval(self) -> tuple[float, float]: ...
    @property
    def estimator(self) -> str: ...
    @property
    def effective_sampling_units(self) -> int: ...
    def __repr__(self) -> str: ...


class RiskValidation:
    @property
    def bump_and_revalue(self) -> DiagnosticEstimate: ...
    @property
    def bump_minus_primary(self) -> DiagnosticEstimate: ...
    def __repr__(self) -> str: ...


class LsmWarning:
    @property
    def kind(self) -> LsmWarningKind: ...
    @property
    def index(self) -> int | None: ...


class LsmFeatureScaling:
    @property
    def mean(self) -> float: ...
    @property
    def population_variance(self) -> float: ...
    @property
    def scale(self) -> float: ...
    @property
    def zero_scale_threshold(self) -> float: ...
    @property
    def inactive(self) -> bool: ...


class ExerciseDecisionDiagnostics:
    @property
    def kind(self) -> ExerciseDecisionKind: ...
    @property
    def continue_all_reason(self) -> LsmWarningKind | None: ...
    @property
    def feature_scalings(self) -> list[LsmFeatureScaling] | None: ...
    @property
    def active_basis_columns(self) -> list[int] | None: ...
    @property
    def pre_excluded_basis_columns(self) -> list[int] | None: ...
    @property
    def pivot_order(self) -> list[int] | None: ...
    @property
    def diagonal_abs(self) -> list[float] | None: ...
    @property
    def rank_threshold(self) -> float | None: ...
    @property
    def rank(self) -> int | None: ...
    @property
    def rank_excluded_basis_columns(self) -> list[int] | None: ...
    @property
    def coefficients(self) -> list[float] | None: ...
    @property
    def residual_sum_squares(self) -> float | None: ...


class ExerciseRegressionDiagnostics:
    @property
    def candidate_rows(self) -> int: ...
    @property
    def itm_rows(self) -> int: ...
    @property
    def feature_count(self) -> int: ...
    @property
    def warnings(self) -> list[LsmWarning]: ...


class EarlyExerciseDiagnostics:
    @property
    def policy_fingerprint(self) -> str: ...
    @property
    def training_random_domain(self) -> RandomDomain: ...
    @property
    def valuation_random_domain(self) -> RandomDomain: ...
    @property
    def training_direction_checksum(self) -> str | None: ...
    @property
    def training_scramble_checksum(self) -> str | None: ...
    @property
    def valuation_direction_checksum(self) -> str | None: ...
    @property
    def valuation_scramble_checksum(self) -> str | None: ...
    @property
    def training_sampling_units(self) -> int: ...
    @property
    def training_trajectories(self) -> int: ...
    @property
    def valuation_sampling_units(self) -> int: ...
    @property
    def valuation_trajectories(self) -> int: ...
    @property
    def in_sample_value(self) -> float: ...
    @property
    def exercise_dates(self) -> list[str]: ...
    @property
    def exercise_counts(self) -> list[int]: ...
    @property
    def exercise_probabilities(self) -> list[float]: ...
    @property
    def stopping_indices(self) -> list[int]: ...
    @property
    def dividend_collisions(self) -> list[bool]: ...
    @property
    def basis_feature_count(self) -> int: ...
    @property
    def basis_max_degree(self) -> int: ...
    @property
    def basis_exponents(self) -> list[list[int]]: ...
    @property
    def itm_abs_tolerance(self) -> float: ...
    @property
    def abs_rank_tolerance(self) -> float: ...
    @property
    def rel_rank_tolerance(self) -> float: ...
    @property
    def max_matrix_elements(self) -> int: ...
    @property
    def decisions(self) -> list[ExerciseDecisionDiagnostics]: ...
    @property
    def regressions(self) -> list[ExerciseRegressionDiagnostics]: ...


class RiskEstimate:
    @property
    def raw(self) -> DiagnosticEstimate: ...
    @property
    def market_scaled(self) -> DiagnosticEstimate: ...
    @property
    def raw_unit(self) -> RiskUnit: ...
    @property
    def market_scaled_unit(self) -> RiskUnit: ...
    def __repr__(self) -> str: ...


class Diagnostics:
    @property
    def master_seed(self) -> int: ...
    @property
    def estimator(self) -> str: ...
    @property
    def scramble_count(self) -> int | None: ...
    @property
    def direction_checksum(self) -> str | None: ...
    @property
    def scramble_checksum(self) -> str | None: ...
    @property
    def policy_version(self) -> int: ...
    @property
    def worker_threads(self) -> int: ...
    @property
    def reduction_block_size(self) -> int: ...
    @property
    def aad_tile_policy_version(self) -> int: ...
    @property
    def aad_tile_capacity(self) -> int: ...
    @property
    def checkpoint_policy_version(self) -> int: ...
    @property
    def checkpoint_interval(self) -> int: ...
    @property
    def antithetic(self) -> bool: ...
    @property
    def discount_region(self) -> str: ...
    @property
    def dividend_region(self) -> str: ...
    @property
    def payoff_fingerprint(self) -> str: ...
    @property
    def valuation_kind(self) -> str: ...
    @property
    def payoff_smoothing_kernel(self) -> str | None: ...
    @property
    def payoff_smoothing_policy_version(self) -> int | None: ...
    @property
    def payoff_smoothing_half_width(self) -> float | None: ...
    @property
    def payoff_smoothing_full_transition_width(self) -> float | None: ...
    @property
    def payoff_smoothing_width_unit(self) -> str | None: ...
    @property
    def payoff_smoothing_price_and_greeks_share_payoff(self) -> bool | None: ...
    @property
    def payoff_smoothing_endpoint_count(self) -> int | None: ...
    @property
    def payoff_smoothing_dividend_jump_count(self) -> int | None: ...
    @property
    def path_state_kind(self) -> str | None: ...
    @property
    def asian_known_observation_count(self) -> int | None: ...
    @property
    def asian_unknown_observation_count(self) -> int | None: ...
    @property
    def asian_known_weight_sum(self) -> float | None: ...
    @property
    def asian_unknown_weight_sum(self) -> float | None: ...
    @property
    def asian_weighted_known_fixing_sum(self) -> float | None: ...
    @property
    def lookback_past_monitoring_count(self) -> int | None: ...
    @property
    def lookback_future_monitoring_count(self) -> int | None: ...
    @property
    def lookback_historical_extremum(self) -> float | None: ...
    @property
    def barrier_bridge_abi(self) -> str | None: ...
    @property
    def barrier_bridge_policy_version(self) -> int | None: ...
    @property
    def barrier_hit_indicator_mode(self) -> str | None: ...
    @property
    def barrier_endpoint_hit_fraction(self) -> float | None: ...
    @property
    def barrier_dividend_jump_hit_fraction(self) -> float | None: ...
    @property
    def barrier_mean_conditional_bridge_hit_weight(self) -> float | None: ...
    @property
    def barrier_mean_interval_count(self) -> float | None: ...
    @property
    def barrier_mean_finite_correction_count(self) -> float | None: ...
    @property
    def barrier_mean_zero_variance_count(self) -> float | None: ...
    @property
    def barrier_mean_survival_underflow_count(self) -> float | None: ...
    @property
    def barrier_mean_certain_survival_count(self) -> float | None: ...
    @property
    def delta_method(self) -> str | None: ...
    @property
    def gamma_method(self) -> str | None: ...
    @property
    def vega_method(self) -> str | None: ...
    @property
    def gamma_spot_bump(self) -> float | None: ...
    @property
    def validation_spot_bump(self) -> float | None: ...
    @property
    def validation_volatility_bump(self) -> float | None: ...
    @property
    def bump_policy_version(self) -> int: ...
    @property
    def exercise_strategy_risk(self) -> ExerciseStrategyRisk | None: ...
    @property
    def stopping_index_risk(self) -> StoppingIndexRisk | None: ...
    @property
    def exercise_policy_fingerprint(self) -> str | None: ...
    @property
    def delta_validation(self) -> RiskValidation | None: ...
    @property
    def gamma_validation(self) -> RiskValidation | None: ...
    @property
    def vega_validation(self) -> RiskValidation | None: ...
    @property
    def warnings(self) -> list[PricingWarning]: ...
    def __repr__(self) -> str: ...


class DiscountCurve:
    def __init__(
        self,
        curve_id: int,
        times: Sequence[float],
        discount_factors: Sequence[float],
    ) -> None: ...
    @property
    def curve_id(self) -> int: ...
    def __repr__(self) -> str: ...


class DividendEvent:
    @staticmethod
    def fixed_cash(event_id: int, ex_time: float, amount: float) -> DividendEvent: ...
    @staticmethod
    def proportional(event_id: int, ex_time: float, beta: float) -> DividendEvent: ...
    @staticmethod
    def fixed_cash_and_proportional(
        event_id: int, ex_time: float, fixed_cash: float, beta: float
    ) -> DividendEvent: ...
    @property
    def event_id(self) -> int: ...
    @property
    def ex_time(self) -> float: ...
    def __repr__(self) -> str: ...


class AsianObservation:
    @staticmethod
    def unknown(date: DateLike, weight: float) -> AsianObservation: ...
    @staticmethod
    def known(date: DateLike, weight: float, fixing: float) -> AsianObservation: ...
    @property
    def date(self) -> str: ...
    @property
    def weight(self) -> float: ...
    @property
    def fixing(self) -> float | None: ...
    def __repr__(self) -> str: ...


class EssviSlice:
    def __init__(self, time: float, theta: float, psi: float, rho_psi: float) -> None: ...
    @property
    def time(self) -> float: ...
    @property
    def theta(self) -> float: ...
    @property
    def psi(self) -> float: ...
    @property
    def rho_psi(self) -> float: ...
    def __repr__(self) -> str: ...


class Product:
    @staticmethod
    def european_vanilla(
        underlying_id: int,
        currency_id: int,
        expiry: DateLike,
        strike: float,
        notional: float,
        side: OptionSide,
    ) -> Product: ...
    @staticmethod
    def american_vanilla(
        underlying_id: int,
        currency_id: int,
        expiry: DateLike,
        strike: float,
        notional: float,
        side: OptionSide,
        exercise_dates: Sequence[DateLike],
    ) -> Product: ...
    @staticmethod
    def digital(
        underlying_id: int,
        currency_id: int,
        expiry: DateLike,
        strike: float,
        payout: float,
        side: OptionSide,
        payout_kind: DigitalPayout,
        *,
        payment_date: DateLike | None = None,
    ) -> Product: ...
    @staticmethod
    def barrier(
        underlying_id: int,
        currency_id: int,
        expiry: DateLike,
        strike: float,
        barrier: float,
        notional: float,
        side: OptionSide,
        direction: BarrierDirection,
        style: BarrierStyle,
        monitoring: BarrierMonitoring,
        monitoring_dates: Sequence[DateLike],
        payment_date: DateLike,
        *,
        rebate: float | None = None,
    ) -> Product: ...
    @staticmethod
    def arithmetic_asian(
        underlying_id: int,
        currency_id: int,
        strike: float,
        notional: float,
        side: OptionSide,
        observations: Sequence[AsianObservation],
        payment_date: DateLike,
    ) -> Product: ...
    @staticmethod
    def fixed_lookback(
        underlying_id: int,
        currency_id: int,
        strike: float,
        notional: float,
        side: OptionSide,
        monitoring_dates: Sequence[DateLike],
        payment_date: DateLike,
        *,
        historical_extremum: float | None = None,
    ) -> Product: ...
    def __repr__(self) -> str: ...


class Market:
    @staticmethod
    def equity(
        currency_id: int,
        underlying_id: int,
        spot: float,
        discount_curve: DiscountCurve,
        dividend_curve: DiscountCurve,
        *,
        discrete_dividends: Sequence[DividendEvent] | None = None,
    ) -> Market: ...
    def __repr__(self) -> str: ...


class Model:
    @staticmethod
    def black_scholes(volatility: float) -> Model: ...
    @staticmethod
    def black_76(volatility: float) -> Model: ...
    @staticmethod
    def local_volatility_from_grid(
        time_nodes: Sequence[float],
        log_forward_moneyness_nodes: Sequence[float],
        local_variances: Sequence[float],
        floor: float,
        cap: float,
    ) -> Model: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def local_volatility_from_grid_with_reporting_basis(
        time_nodes: Sequence[float],
        log_forward_moneyness_nodes: Sequence[float],
        local_variances: Sequence[float],
        floor: float,
        cap: float,
        reporting_maturity_nodes: Sequence[float],
        reporting_log_forward_moneyness_nodes: Sequence[float],
        reporting_implied_volatilities: Sequence[float],
    ) -> Model: ...
    @staticmethod
    def local_volatility_from_essvi(
        slices: Sequence[EssviSlice],
        terminal_theta_slope: float,
        time_nodes: Sequence[float],
        log_forward_moneyness_nodes: Sequence[float],
        floor: float,
        cap: float,
    ) -> Model: ...
    @staticmethod
    def local_volatility_from_standard_ssvi_power_law(
        theta_times: Sequence[float],
        theta_values: Sequence[float],
        terminal_theta_slope: float,
        rho: float,
        eta: float,
        gamma: float,
        time_nodes: Sequence[float],
        log_forward_moneyness_nodes: Sequence[float],
        floor: float,
        cap: float,
    ) -> Model: ...
    @staticmethod
    def local_volatility_from_standard_ssvi_heston_like(
        theta_times: Sequence[float],
        theta_values: Sequence[float],
        terminal_theta_slope: float,
        rho: float,
        lambda_: float,
        time_nodes: Sequence[float],
        log_forward_moneyness_nodes: Sequence[float],
        floor: float,
        cap: float,
    ) -> Model: ...


class Engine:
    @staticmethod
    def pseudo_monte_carlo(
        master_seed: int,
        independent_sampling_units: int,
        *,
        antithetic: bool = False,
        brownian_bridge: bool = False,
    ) -> Engine: ...
    @staticmethod
    def randomized_quasi_monte_carlo(
        points_per_scramble: int,
        master_scramble_seed: int,
        *,
        scramble_count: int = 16,
        antithetic: bool = False,
        brownian_bridge: bool = True,
    ) -> Engine: ...
    def __repr__(self) -> str: ...


class LsmConfig:
    def __init__(
        self,
        training_engine: Engine,
        *,
        state_variables: Sequence[LsmStateVariable] | None = None,
        max_degree: int = 3,
        max_basis_columns: int = 64,
        max_total_exponents: int = 64,
        itm_abs_tolerance: float = 0.0,
        abs_rank_tolerance: float = 1.0e-14,
        rel_rank_tolerance: float = 1.0e-12,
        max_matrix_elements: int = 1_000_000,
    ) -> None: ...
    @property
    def state_variables(self) -> list[LsmStateVariable]: ...
    @property
    def max_degree(self) -> int: ...
    @property
    def basis_exponents(self) -> list[list[int]]: ...
    @property
    def itm_abs_tolerance(self) -> float: ...
    @property
    def abs_rank_tolerance(self) -> float: ...
    @property
    def rel_rank_tolerance(self) -> float: ...
    @property
    def max_matrix_elements(self) -> int: ...
    @property
    def fingerprint(self) -> str: ...
    def __repr__(self) -> str: ...


class RiskRequest:
    def __init__(
        self,
        *,
        delta: bool = False,
        gamma_relative_bump: float | None = None,
        gamma_absolute_bump: float | None = None,
        vega: bool = False,
        vega_kt_maturity_nodes: Sequence[DateLike] | None = None,
        vega_kt_log_forward_moneyness_nodes: Sequence[float] | None = None,
        vega_kt_relative_density_threshold: float | None = None,
        vega_kt_full_bucket_covariance: bool = False,
        payoff_smoothing_half_width: float | None = None,
        payoff_smoothing_width_ladder: Sequence[float] | None = None,
        smile_dynamics: SmileDynamics = "sticky_log_moneyness",
        checkpoint_interval: int | None = None,
        aad_tile_capacity: int | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...


class PricingRequest:
    def __init__(
        self,
        valuation_date: DateLike,
        product: Product,
        market: Market,
        model: Model,
        engine: Engine,
        risk: RiskRequest,
        *,
        lsm: LsmConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json: str) -> PricingRequest: ...
    def to_json(self) -> str: ...
    def to_pretty_json(self) -> str: ...
    @property
    def fingerprint(self) -> str: ...
    def __repr__(self) -> str: ...


class PricingPlan:
    @staticmethod
    def compile(
        request: PricingRequest,
        *,
        worker_threads: int,
        reduction_block_size: int | None = None,
    ) -> PricingPlan: ...
    def evaluate(self) -> PricingResult: ...
    def evaluate_width_ladder(self) -> WidthLadderResult: ...
    @property
    def request_fingerprint(self) -> str: ...
    @property
    def plan_fingerprint(self) -> str: ...
    @property
    def worker_threads(self) -> int: ...
    @property
    def reduction_block_size(self) -> int: ...
    @property
    def request_original_schema_version(self) -> int: ...
    @property
    def request_current_schema_version(self) -> int: ...
    @property
    def request_migration_ids(self) -> list[str]: ...
    @property
    def request_pre_migration_fingerprint(self) -> str: ...
    @property
    def request_post_migration_fingerprint(self) -> str: ...
    def __repr__(self) -> str: ...


class WidthLadderDifference:
    @property
    def price(self) -> float: ...
    @property
    def delta(self) -> float | None: ...
    @property
    def gamma(self) -> float | None: ...
    @property
    def vega(self) -> float | None: ...
    def __repr__(self) -> str: ...


class WidthLadderEntry:
    @property
    def half_width(self) -> float: ...
    @property
    def result(self) -> PricingResult: ...
    @property
    def adjacent_difference(self) -> WidthLadderDifference | None: ...
    def __repr__(self) -> str: ...


class WidthLadderResult:
    @property
    def primary(self) -> PricingResult: ...
    @property
    def entries(self) -> list[WidthLadderEntry]: ...
    def __repr__(self) -> str: ...


class VegaKtCoordinate:
    @property
    def maturity(self) -> float: ...
    @property
    def log_moneyness(self) -> float: ...
    @property
    def implied_volatility(self) -> float: ...
    def __repr__(self) -> str: ...


class VegaKtBucketEstimate:
    @property
    def raw_mean(self) -> float: ...
    @property
    def market_scaled_mean(self) -> float: ...
    @property
    def sample_variance(self) -> float | None: ...
    @property
    def price_covariance(self) -> float | None: ...
    def __repr__(self) -> str: ...


class VegaKtReportingStats:
    @property
    def left_edge_count(self) -> int: ...
    @property
    def right_edge_count(self) -> int: ...
    @property
    def left_edge_sensitivity(self) -> float: ...
    @property
    def right_edge_sensitivity(self) -> float: ...
    def __repr__(self) -> str: ...


class VegaKtProjection:
    @property
    def scalar_vega(self) -> float: ...
    @property
    def signed_residual(self) -> float: ...
    @property
    def pre_projection(self) -> float: ...
    @property
    def reporting_stats(self) -> VegaKtReportingStats: ...
    def __repr__(self) -> str: ...


class VegaKtResidualDiagnostics:
    @property
    def active_domain_start_index(self) -> int: ...
    @property
    def active_domain_end_index(self) -> int: ...
    @property
    def active_domain_forward_index(self) -> int: ...
    @property
    def excluded_probability_mass(self) -> float: ...
    @property
    def signed_residual(self) -> float: ...
    @property
    def pre_projection(self) -> float: ...
    @property
    def reporting_stats(self) -> VegaKtReportingStats: ...
    def __repr__(self) -> str: ...


class VegaKtResult:
    @property
    def coordinates(self) -> list[VegaKtCoordinate]: ...
    @property
    def estimates(self) -> list[VegaKtBucketEstimate]: ...
    @property
    def raw_buckets(self) -> list[float]: ...
    @property
    def full_bucket_covariance(self) -> list[float | None] | None: ...
    @property
    def covariance_layout(self) -> VegaKtCovarianceLayout: ...
    @property
    def projection(self) -> VegaKtProjection: ...
    @property
    def residual_diagnostics(self) -> VegaKtResidualDiagnostics: ...
    @property
    def raw_unit(self) -> VegaKtUnit: ...
    @property
    def market_scaled_unit(self) -> VegaKtUnit: ...
    @property
    def policy_label(self) -> str: ...
    @property
    def truncation_order(self) -> str: ...
    def __repr__(self) -> str: ...


class PricingResult:
    @staticmethod
    def from_json(json: str) -> PricingResult: ...
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def confidence_interval(self) -> tuple[float, float]: ...
    @property
    def estimate(self) -> DiagnosticEstimate: ...
    @property
    def delta(self) -> RiskEstimate | None: ...
    @property
    def delta_raw(self) -> float | None: ...
    @property
    def delta_market_scaled(self) -> float | None: ...
    @property
    def gamma(self) -> RiskEstimate | None: ...
    @property
    def gamma_raw(self) -> float | None: ...
    @property
    def gamma_market_scaled(self) -> float | None: ...
    @property
    def vega(self) -> RiskEstimate | None: ...
    @property
    def vega_raw(self) -> float | None: ...
    @property
    def vega_market_scaled(self) -> float | None: ...
    @property
    def vega_kt(self) -> VegaKtResult | None: ...
    @property
    def sampling_variance(self) -> float: ...
    @property
    def estimator_variance(self) -> float: ...
    @property
    def independent_sampling_units(self) -> int: ...
    @property
    def evaluated_paths(self) -> int: ...
    @property
    def diagnostics(self) -> Diagnostics: ...
    @property
    def early_exercise_diagnostics(self) -> EarlyExerciseDiagnostics | None: ...
    @property
    def warnings(self) -> list[PricingWarning]: ...
    @property
    def replay_schema_version(self) -> int: ...
    @property
    def replay_request_fingerprint(self) -> str: ...
    @property
    def replay_library_version(self) -> str: ...
    @property
    def replay_platform(self) -> str: ...
    @property
    def replay_original_schema_version(self) -> int: ...
    @property
    def replay_current_schema_version(self) -> int: ...
    @property
    def replay_migration_ids(self) -> list[str]: ...
    @property
    def replay_pre_migration_fingerprint(self) -> str: ...
    @property
    def replay_post_migration_fingerprint(self) -> str: ...
    def to_json(self) -> str: ...
    def to_pretty_json(self) -> str: ...
    def __repr__(self) -> str: ...


def version() -> str: ...
def request_json_schema() -> str: ...
def result_json_schema() -> str: ...

class CorrelationSchedule:
    def __init__(
        self, underlying_ids: Sequence[int], effective_dates: Sequence[DateLike],
        matrices: Sequence[Sequence[Sequence[float]]], *, symmetry_abs_tol: float,
        diagonal_abs_tol: float, psd_abs_tol: float, psd_rel_tol: float,
        zero_pivot_abs_tol: float, zero_pivot_rel_tol: float,
    ) -> None: ...
    @property
    def underlying_ids(self) -> list[int]: ...
    @property
    def effective_dates(self) -> list[str]: ...
    @property
    def matrices(self) -> list[list[list[float]]]: ...
    @property
    def raw_matrices(self) -> list[list[list[float]]]: ...
    @property
    def lower_factors(self) -> list[list[list[float]]]: ...
    @property
    def ranks(self) -> list[int]: ...
    @property
    def pivots(self) -> list[list[float]]: ...
    @property
    def zero_pivots(self) -> list[list[int]]: ...
    @property
    def maximum_adjustments(self) -> list[float]: ...

class AutocallObservation:
    def __init__(
        self, date: DateLike, payment_date: DateLike, *, coupon_amount: float,
        coupon_level: float, call_level: float | None = None,
        call_coupon_amount: float = 0.0,
    ) -> None: ...

class MultiAssetProduct:
    @staticmethod
    def basket(
        underlying_ids: Sequence[int], weights: Sequence[float], scales: Sequence[float],
        side: OptionSide, strike: float, expiry: DateLike, payment_date: DateLike, *,
        currency_id: int = 1, notional: float = 1.0,
        smoothing_half_width: float | None = None,
    ) -> MultiAssetProduct: ...
    @staticmethod
    def worst_of(
        underlying_ids: Sequence[int], reference_levels: Sequence[float], side: OptionSide,
        strike: float, expiry: DateLike, payment_date: DateLike, *, currency_id: int = 1,
        notional: float = 1.0, smoothing_half_width: float | None = None,
    ) -> MultiAssetProduct: ...
    @staticmethod
    def autocallable(
        underlying_ids: Sequence[int], reference_levels: Sequence[float],
        observations: Sequence[AutocallObservation], maturity: DateLike,
        maturity_payment: DateLike, *, notional: float, final_barrier: float,
        memory: bool, on_autocall: Literal["forfeit", "pay"],
        on_maturity: Literal["forfeit", "pay"], currency_id: int = 1,
        smoothing_half_width: float | None = None,
    ) -> MultiAssetProduct: ...
    @property
    def underlying_ids(self) -> list[int]: ...

class MultiAssetPlan:
    @property
    def local_correlation_calibration(self) -> LocalCorrelationCalibration | None: ...
    @staticmethod
    def compile(
        valuation_date: DateLike, product: MultiAssetProduct, markets: Sequence[Market],
        models: Sequence[Model], correlations: CorrelationSchedule, engine: Engine, *,
        maximum_step: float, worker_threads: int = 1, reduction_block_size: int = 4096,
        lsv_configs: Sequence[MultiAssetLsvConfig | MultiAssetLsv2FactorConfig | MultiAssetRoughLsvConfig | None] | None = None,
        driver_correlations: Sequence[Sequence[Sequence[float]]] | None = None,
        rate_model: HullWhiteModel | None = None,
        rate_correlations: Sequence[float] | None = None,
        lsv_targets: Sequence[HullWhiteLsvTarget | None] | None = None,
        local_correlation: LocalCorrelationConfig | None = None,
    ) -> MultiAssetPlan: ...
    def evaluate(self) -> MultiAssetPrice: ...
    def evaluate_aad(self, *, gamma_relative_bump: float | None = None) -> MultiAssetPrice: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def correlation_entry_indices(self) -> list[int]: ...
    @property
    def random_factor_count(self) -> int: ...
    @property
    def lsv_calibrations(self) -> list[MultiAssetLsvCalibration | None]: ...
    @property
    def has_hull_white(self) -> bool: ...
    @property
    def hull_white_calibrations(self) -> list[MultiAssetHullWhiteCalibration | None]: ...
    @property
    def lsv_driver_correlations(self) -> list[list[list[float]]]: ...
    @property
    def lsv_transition_covariances(self) -> list[list[list[float]]]: ...
    @property
    def underlying_ids(self) -> list[int]: ...

class MultiAssetRisk:
    @property
    def hull_white_lsv(self) -> MultiAssetHullWhiteLsvRisk | None: ...
    @property
    def lsv_local_variance(self) -> MultiAssetLsvRisk | None: ...
    @property
    def underlying_id(self) -> int: ...
    @property
    def delta(self) -> DiagnosticEstimate: ...
    @property
    def delta_per_one_percent_spot(self) -> DiagnosticEstimate: ...
    @property
    def bs_vega(self) -> DiagnosticEstimate | None: ...
    @property
    def bs_vega_per_vol_point(self) -> DiagnosticEstimate | None: ...
    @property
    def local_variance(self) -> list[DiagnosticEstimate]: ...
    @property
    def local_variance_time_nodes(self) -> list[float]: ...
    @property
    def local_variance_log_moneyness_nodes(self) -> list[float]: ...

class MultiAssetPrice:
    @property
    def local_correlation_risk(self) -> LocalCorrelationRisk | None: ...
    @property
    def hull_white_curve_risk(self) -> MultiAssetHullWhiteCurveRisk | None: ...
    @property
    def lsv_leverage_boundary_counts(self) -> list[float]: ...
    @property
    def value(self) -> float: ...
    @property
    def standard_error(self) -> float: ...
    @property
    def price(self) -> DiagnosticEstimate: ...
    @property
    def risks(self) -> list[MultiAssetRisk]: ...
    @property
    def gamma(self) -> list[list[DiagnosticEstimate]]: ...
    @property
    def gamma_relative_bump(self) -> float | None: ...
    @property
    def underlying_ids(self) -> list[int]: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def evaluated_paths(self) -> int: ...
    @property
    def worker_threads(self) -> int: ...
    @property
    def reduction_block_size(self) -> int: ...
    @property
    def local_variance_boundary_counts(self) -> list[float]: ...
    @property
    def direction_checksum(self) -> str | None: ...
    @property
    def scramble_checksum(self) -> str | None: ...

class MultiAssetLsvConfig:
    def __init__(self, *, mean_reversion: float, vol_of_vol: float, correlation: float,
                 particle_count: int, calibration_seed: int, log_bandwidth: float,
                 minimum_effective_samples: float, retain_reverse_trace: bool = False) -> None: ...
    @property
    def mean_reversion(self) -> float: ...
    @property
    def vol_of_vol(self) -> float: ...
    @property
    def correlation(self) -> float: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def log_bandwidth(self) -> float: ...
    @property
    def minimum_effective_samples(self) -> float: ...
    @property
    def retain_reverse_trace(self) -> bool: ...

class MultiAssetRoughLsvConfig:
    """Rough-LSV under common HW; vol_of_vol is eta, the log-variance coefficient."""
    def __init__(self, *, hurst: float, vol_of_vol: float, correlation: float,
                 particle_count: int, calibration_seed: int, log_bandwidth: float,
                 minimum_effective_samples: float, retain_reverse_trace: bool = False) -> None: ...
    @property
    def hurst(self) -> float: ...
    @property
    def vol_of_vol(self) -> float: ...
    @property
    def correlation(self) -> float: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def log_bandwidth(self) -> float: ...
    @property
    def minimum_effective_samples(self) -> float: ...
    @property
    def retain_reverse_trace(self) -> bool: ...

class MultiAssetLsv2FactorConfig:
    def __init__(self, *, mean_reversions: Sequence[float], vol_of_vol: float, mixing_weight: float,
                 spot_correlations: Sequence[float], factor_correlation: float,
                 particle_count: int, calibration_seed: int, log_bandwidth: float,
                 minimum_effective_samples: float, retain_reverse_trace: bool = False) -> None: ...
    @property
    def mean_reversions(self) -> list[float]: ...
    @property
    def vol_of_vol(self) -> float: ...
    @property
    def spot_correlations(self) -> list[float]: ...
    @property
    def mixing_weight(self) -> float: ...
    @property
    def factor_correlation(self) -> float: ...
    @property
    def normalized_weights(self) -> list[float]: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def log_bandwidth(self) -> float: ...
    @property
    def minimum_effective_samples(self) -> float: ...
    @property
    def retain_reverse_trace(self) -> bool: ...

class MultiAssetLsvCalibration:
    @property
    def volatility_factor_count(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float]: ...
    @property
    def effective_samples(self) -> list[float]: ...
    @property
    def donor_nodes(self) -> list[int]: ...
    @property
    def extrapolated(self) -> list[bool]: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...
    @property
    def extrapolated_nodes(self) -> list[int]: ...
    @property
    def particle_mean_normalized_f(self) -> list[float]: ...
    @property
    def method(self) -> str: ...

class MultiAssetLsvRisk:
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def node_adjoints(self) -> list[float]: ...
    @property
    def standard_errors(self) -> list[float] | None: ...
    @property
    def method(self) -> str: ...


class MultiAssetHullWhiteCalibration:
    @property
    def volatility_factor_count(self) -> int: ...
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_moneyness_nodes(self) -> list[float]: ...
    @property
    def squared_leverage(self) -> list[float]: ...
    @property
    def minimum_effective_samples(self) -> list[float]: ...
    @property
    def fallback_nodes(self) -> list[int]: ...
    @property
    def mean_relative_discount(self) -> list[float]: ...
    @property
    def mean_discounted_normalized_equity(self) -> list[float]: ...
    @property
    def conditional_second_moments(self) -> list[float]: ...
    @property
    def rate_corrections(self) -> list[float]: ...
    @property
    def retains_reverse_trace(self) -> bool: ...


class MultiAssetHullWhiteLsvRisk:
    @property
    def forward_log_density_adjoints(self) -> list[float]: ...
    @property
    def density_standard_errors(self) -> list[float] | None: ...
    @property
    def vega_kt_raw(self) -> list[float] | None: ...
    @property
    def vega_kt_market_scaled(self) -> list[float] | None: ...
    @property
    def vega_kt_standard_errors(self) -> list[float] | None: ...
    @property
    def vega_kt_maturity_nodes(self) -> list[float]: ...
    @property
    def vega_kt_log_moneyness_nodes(self) -> list[float]: ...
    @property
    def parallel_vega(self) -> float | None: ...
    @property
    def parallel_vega_standard_error(self) -> float | None: ...
    @property
    def method(self) -> str: ...


class MultiAssetHullWhiteCurveRisk:
    @property
    def discount_time_nodes(self) -> list[float]: ...
    @property
    def discount_log_df_adjoints(self) -> list[DiagnosticEstimate]: ...
    @property
    def discount_node_dv01(self) -> list[DiagnosticEstimate]: ...
    @property
    def dividend_time_nodes(self) -> list[list[float]]: ...
    @property
    def dividend_log_df_adjoints(self) -> list[list[DiagnosticEstimate]]: ...

class LocalCorrelationConfig:
    def __init__(self, *, basket_weights: Sequence[float], target_model: Model,
        second_correlations: CorrelationSchedule, particle_count: int,
        calibration_seed: int, log_bandwidth: float, minimum_effective_samples: float,
        feasibility: str = "reject", minimum_variance_span: float = 1e-12,
        retain_reverse_trace: bool = False,
        second_driver_correlations: Sequence[Sequence[Sequence[float]]] | None = None,
        hull_white_target: HullWhiteLsvTarget | None = None) -> None: ...
    @property
    def second_driver_correlations(self) -> list[list[list[float]]] | None: ...
    @property
    def hull_white_target(self) -> HullWhiteLsvTarget | None: ...
    @property
    def basket_weights(self) -> list[float]: ...
    @property
    def target_model(self) -> Model: ...
    @property
    def second_correlations(self) -> CorrelationSchedule: ...
    @property
    def particle_count(self) -> int: ...
    @property
    def calibration_seed(self) -> int: ...
    @property
    def log_bandwidth(self) -> float: ...
    @property
    def minimum_effective_samples(self) -> float: ...
    @property
    def feasibility(self) -> str: ...
    @property
    def minimum_variance_span(self) -> float: ...
    @property
    def retain_reverse_trace(self) -> bool: ...

class LocalCorrelationCalibration:
    @property
    def time_nodes(self) -> list[float]: ...
    @property
    def log_nodes(self) -> list[float]: ...
    @property
    def mixing_coefficients(self) -> list[float]: ...
    @property
    def endpoint_variances(self) -> list[list[float]]: ...
    @property
    def target_variances(self) -> list[float]: ...
    @property
    def attained_variances(self) -> list[float]: ...
    @property
    def variance_residuals(self) -> list[float]: ...
    @property
    def raw_mixing(self) -> list[float]: ...
    @property
    def effective_samples(self) -> list[float]: ...
    @property
    def source_nodes(self) -> list[int]: ...
    @property
    def fallback_nodes(self) -> list[bool]: ...
    @property
    def projected_nodes(self) -> list[bool]: ...
    @property
    def unidentifiable_nodes(self) -> list[bool]: ...
    @property
    def particle_means(self) -> list[list[float]]: ...
    @property
    def retains_reverse_trace(self) -> bool: ...
    @property
    def rate_corrections(self) -> list[float]: ...
    def driver_correlation_at(self, time: float, log_basket: float) -> list[list[float]]: ...
    def correlation_at(self, time: float, log_basket: float) -> list[list[float]]: ...

class LocalCorrelationRisk:
    @property
    def basket_hull_white(self) -> MultiAssetHullWhiteLsvRisk | None: ...
    @property
    def asset_hull_white(self) -> list[MultiAssetHullWhiteLsvRisk | None]: ...
    @property
    def basket_time_nodes(self) -> list[float]: ...
    @property
    def basket_log_nodes(self) -> list[float]: ...
    @property
    def basket_variance_adjoints(self) -> list[float]: ...
    @property
    def basket_standard_errors(self) -> list[float] | None: ...
    @property
    def asset_adjoints(self) -> list[list[float]]: ...
    @property
    def asset_standard_errors(self) -> list[list[float]] | None: ...
    @property
    def asset_time_nodes(self) -> list[list[float]]: ...
    @property
    def asset_log_nodes(self) -> list[list[float]]: ...
    @property
    def method(self) -> str: ...
