[package]
name = "pricing-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "rust_pricing"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pricing.workspace = true
pyo3.workspace = true

[lints]
workspace = true
