[package]
name = "pricing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
pricing-numerics.workspace = true
rayon.workspace = true
blake3.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
