[package]
name = "pricing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
pricing-core.workspace = true
pricing-market.workspace = true
pricing-product.workspace = true
pricing-models.workspace = true
pricing-mc.workspace = true
pricing-risk.workspace = true

[lints]
workspace = true
