"""Rebuild the retained Bergomi calibration quality document from a run log.

The acceptance test prints one ``BERGOMI_RUN`` line per complete
calibration-and-pricing run and one ``BERGOMI_QUALITY`` line per surface. This
turns those lines plus the provenance that is not in them into
``design/validation/bergomi-calibration-quality-results.json``, so the retained
evidence is regenerated by a command rather than assembled by hand.

The log is the test's own stdout, for example the artifact CI retains:

    cargo test --locked --release -p pricing --test bergomi_calibration_quality \\
        iv_round_trip_ -- --ignored --nocapture --test-threads=1 \\
        2>&1 | tee bergomi-calibration-quality.log
    python3 scripts/summarize_bergomi_quality.py --log bergomi-calibration-quality.log

Only ``iv_round_trip_`` output belongs in the document. A log that also holds
refinement, bandwidth-scan or high-vol-of-vol lines carries reports that are
not acceptance runs, so pass exactly the acceptance log.

``--platform`` and ``--compiler`` default to the toolchain running this script.
When summarizing a log produced on another machine, pass that machine's values;
recording the local toolchain for a foreign log would be a false provenance
claim.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEST_FILE = "crates/pricing/tests/bergomi_calibration_quality.rs"
RESULTS_FILE = "design/validation/bergomi-calibration-quality-results.json"
RUN_PREFIX = "BERGOMI_RUN "
QUALITY_PREFIX = "BERGOMI_QUALITY "
IV_BP = 1e-4
DEFAULT_EVIDENCE_SCOPE = (
    "Local test-only validation; not market-data calibration, model production "
    "acceptance or multi-platform CI evidence."
)
# Retained under the document's own names, which predate the test's Model struct.
FACTOR_KEYS = {
    "mean_reversion": "mean_reversion",
    "nu": "volatility_multiplier_nu",
    "rho": "correlation",
}


class SummaryError(RuntimeError):
    """A log or a repository state that cannot produce an honest document."""


def payloads(log: str, prefix: str) -> list[dict]:
    found = []
    for number, line in enumerate(log.splitlines(), start=1):
        index = line.find(prefix)
        if index < 0:
            continue
        text = line[index + len(prefix) :].strip()
        try:
            found.append(json.loads(text))
        except json.JSONDecodeError as error:
            raise SummaryError(f"line {number}: {prefix.strip()} is not JSON: {error}")
    return found


def sorted_payload(payload: dict) -> dict:
    """Re-key a payload alphabetically, matching the retained document."""
    return json.loads(json.dumps(payload, sort_keys=True))


def factor_of(reports: list[dict]) -> dict:
    models = {json.dumps(r["model"], sort_keys=True) for r in reports if "model" in r}
    if not models:
        raise SummaryError(
            "no acceptance report carries a model; this log predates the model "
            "field and cannot be summarized into the current document"
        )
    if len(models) > 1:
        raise SummaryError(
            f"acceptance reports carry {len(models)} distinct models; a log mixing "
            "the stressed vol-of-vol or refinement reports with the acceptance "
            "gates cannot be summarized"
        )
    model = json.loads(models.pop())
    missing = set(FACTOR_KEYS) - set(model)
    if missing:
        raise SummaryError(f"model is missing {sorted(missing)}")
    return {FACTOR_KEYS[k]: model[k] for k in FACTOR_KEYS}


def seeds_of(runs: list[dict]) -> list[int]:
    seeds: list[int] = []
    for run in runs:
        seed = run.get("run", {}).get("calibration_seed")
        if seed is None:
            raise SummaryError("BERGOMI_RUN line has no run.calibration_seed")
        if seed not in seeds:
            seeds.append(seed)
    if not seeds:
        raise SummaryError("no BERGOMI_RUN lines; the log is not an acceptance run")
    return seeds


def check(document: dict) -> None:
    """Reject a document that would misrepresent the run it came from."""
    reports = document["acceptance_reports"]
    if not reports:
        raise SummaryError("no BERGOMI_QUALITY lines in the log")
    smiles = [r["smile"] for r in reports]
    if len(set(smiles)) != len(smiles):
        raise SummaryError(f"a surface is reported more than once: {smiles}")
    seeds = document["calibration_seeds"]
    for report in reports:
        quotes = len(report["nodes"])
        if quotes == 0:
            raise SummaryError(f"{report['smile']} has no nodes")
        if len(report["martingales"]) == 0:
            raise SummaryError(f"{report['smile']} has no martingales")
        # serde_json has no NaN or Infinity literal and writes null for both, so
        # a null is how a nonfinite metric reaches this document. Python's parser
        # does accept a bare NaN token, so reject that shape as well.
        for label, entries in (("node", report["nodes"]), ("martingale", report["martingales"])):
            for entry in entries:
                for key, value in entry.items():
                    if value is None:
                        raise SummaryError(
                            f"{report['smile']} {label} {key} is null, which is how "
                            "a nonfinite value is written; the run is not reportable"
                        )
                    if isinstance(value, float) and value != value:
                        raise SummaryError(f"{report['smile']} {label} {key} is NaN")
        if len(seeds) * quotes == 0:
            raise SummaryError("empty seed or quote panel")


def rustc_version() -> tuple[str, str]:
    try:
        text = subprocess.run(
            ["rustc", "-vV"], capture_output=True, text=True, check=True
        ).stdout
    except (OSError, subprocess.CalledProcessError) as error:
        raise SummaryError(
            f"cannot read the local toolchain ({error}); pass --platform and --compiler"
        )
    host = ""
    version = ""
    for line in text.splitlines():
        if line.startswith("host: "):
            host = line[len("host: ") :].strip()
        elif line.startswith("rustc "):
            version = line.strip()
    if not host or not version:
        raise SummaryError("could not parse `rustc -vV`; pass --platform and --compiler")
    return host, version


def baseline(ref: str) -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", ref], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SummaryError(
            f"cannot resolve the source baseline {ref!r} ({error}); pass --source-baseline"
        )


def build(
    log: str,
    *,
    source_baseline: str,
    platform: str,
    compiler: str,
    mode: str,
    evidence_scope: str,
    test_source: bytes,
) -> dict:
    reports = [sorted_payload(p) for p in payloads(log, QUALITY_PREFIX)]
    document = {
        "source_baseline": source_baseline,
        "test_file": TEST_FILE,
        "test_source_sha256": hashlib.sha256(test_source).hexdigest(),
        "platform": platform,
        "compiler": compiler,
        "mode": mode,
        "calibration_seeds": seeds_of(payloads(log, RUN_PREFIX)),
        "factor": factor_of(reports),
        "iv_bp": IV_BP,
        "acceptance_reports": reports,
        "evidence_scope": evidence_scope,
    }
    check(document)
    return document


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--log", required=True, type=Path, help="acceptance run stdout")
    parser.add_argument("--out", type=Path, default=ROOT / RESULTS_FILE)
    parser.add_argument("--test-file", type=Path, default=ROOT / TEST_FILE)
    parser.add_argument("--source-baseline", help="commit the run was made against")
    parser.add_argument("--baseline-ref", default="origin/main")
    parser.add_argument("--platform", help="target triple the run executed on")
    parser.add_argument("--compiler", help="`rustc -vV` version line of that run")
    parser.add_argument("--mode", default="release")
    parser.add_argument("--evidence-scope", default=DEFAULT_EVIDENCE_SCOPE)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output file is not already what this log produces",
    )
    args = parser.parse_args(argv)

    try:
        host, version = ("", "")
        if not args.platform or not args.compiler:
            host, version = rustc_version()
        document = build(
            args.log.read_text(),
            source_baseline=args.source_baseline or baseline(args.baseline_ref),
            platform=args.platform or host,
            compiler=args.compiler or version,
            mode=args.mode,
            evidence_scope=args.evidence_scope,
            test_source=args.test_file.read_bytes(),
        )
    except (SummaryError, OSError) as error:
        print(f"summarize_bergomi_quality: {error}", file=sys.stderr)
        return 1

    text = json.dumps(document, indent=2) + "\n"
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != text:
            print(
                f"summarize_bergomi_quality: {args.out} is stale for this log",
                file=sys.stderr,
            )
            return 1
        print(f"{args.out} matches the log")
        return 0
    args.out.write_text(text)
    surfaces = ", ".join(r["smile"] for r in document["acceptance_reports"])
    print(f"wrote {args.out} ({surfaces}; seeds {document['calibration_seeds']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
